repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^tests/fixtures/

-   repo: local

    hooks:
        - id: autoflake
          name: autoflake
          entry: autoflake
          language: system
          types: [python]
          args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

        - id: flake8
          name: flake8
          entry: flake8
          language: system
          types: [python]
          args: [--max-line-length=79, --exclude=*.git *.html __pycache__ docs build dist */migrations/*]

        - id: pyupgrade
          name: pyupgrade
          entry: pyupgrade
          language: system
          types: [python]
          args: [--py310-plus]

        - id: reorder-python-imports
          name: reorder-python-imports
          entry: reorder-python-imports
          language: system
          types: [python]
          args: [--py310-plus]
